# Generated by Django 3.2.5 on 2021-07-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210707_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
