# Generated by Django 3.2.5 on 2021-07-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_delete_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
