# Generated by Django 3.2.5 on 2021-07-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210707_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='Greenville', max_length=64),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(default='SC', max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='zip_code',
            field=models.CharField(default='43701', max_length=5),
        ),
    ]
