# Generated by Django 3.2.5 on 2021-07-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210708_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='1234 Alligator Highway', max_length=64),
        ),
    ]
