# Generated by Django 3.2.5 on 2021-07-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
