# Generated by Django 3.2.5 on 2021-07-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20210709_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='organization',
        ),
    ]
