# Generated by Django 3.2.5 on 2021-07-11 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0018_alter_attendance_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_organizer', to=settings.AUTH_USER_MODEL),
        ),
    ]
