# Generated by Django 3.2.5 on 2021-07-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_attendance_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='state',
        ),
        migrations.RemoveField(
            model_name='event',
            name='zip_code',
        ),
    ]
