# Generated by Django 3.2.5 on 2021-07-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20210713_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
