# Generated by Django 3.2.5 on 2021-07-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_event_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='position',
        ),
    ]
