# Generated by Django 3.2.5 on 2021-07-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_remove_event_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='position',
            field=models.JSONField(null=True),
        ),
    ]
