# Generated by Django 3.2.5 on 2021-07-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_event_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='profile_picture',
            field=models.ImageField(default='profiles/volunteerdefault.jpeg', upload_to='profiles/'),
        ),
    ]
