# Generated by Django 3.2.5 on 2021-07-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profiles/volunteerdefault.jpeg', upload_to='profiles/'),
        ),
    ]
