# Generated by Django 3.2.5 on 2021-07-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210706_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_organizer',
        ),
    ]
