# Generated by Django 3.2.5 on 2021-07-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
    ]
