# Generated by Django 3.2.5 on 2021-07-09 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
